import os

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv
from google import genai


load_dotenv()


router = APIRouter()


# Get Gemini settings from .env
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_MODEL = os.getenv(
    "GEMINI_MODEL",
    "gemini-2.5-flash"
)


# -----------------------------
# Request model
# -----------------------------

class DocumentRequest(BaseModel):
    document_type: str
    parties: str
    terms: str
    effective_date: str


# -----------------------------
# Generate legal document
# -----------------------------

@router.post("/generate")
def generate_document(request: DocumentRequest):

    if not GEMINI_API_KEY:
        raise HTTPException(
            status_code=500,
            detail="Gemini API key is missing. Please add it to the .env file."
        )

    try:

        # Create Gemini client
        client = genai.Client(
            api_key=GEMINI_API_KEY
        )

        # Prompt for Gemini
        prompt = f"""
You are LegalEase, an AI-powered legal document drafting assistant.

Create a professional LEGAL DOCUMENT DRAFT based on the information below.

DOCUMENT TYPE:
{request.document_type}

PARTIES:
{request.parties}

EFFECTIVE DATE:
{request.effective_date}

TERMS AND CONDITIONS:
{request.terms}

Requirements:

1. Create a professional legal document.
2. Use clear and formal legal language.
3. Use a suitable title.
4. Divide the document into numbered sections.
5. Include all important information provided by the user.
6. Do not invent personal information.
7. If information is missing, use [INSERT INFORMATION].
8. Add suitable clauses based on the supplied information.
9. Add signature sections for the parties.
10. Do not claim that the document has been reviewed by a lawyer.
11. Do not claim that the document is guaranteed to be legally valid.
12. End the document with:

"Draft generated by LegalEase AI.
Please review this document with a qualified legal professional before use."

Return only the document.
"""

        # Ask Gemini to generate the document
        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=prompt
        )

        document = response.text

        if not document:
            raise HTTPException(
                status_code=500,
                detail="Gemini returned an empty response."
            )

        return {
            "success": True,
            "document": document
        }

    except Exception as error:

        raise HTTPException(
            status_code=500,
            detail=str(error)
        )


# -----------------------------
# API test route
# -----------------------------

@router.get("/test")
def test_api():

    return {
        "message": "LegalEase API is working",
        "status": "success"
    }